# fly.toml app configuration file generated for sample-sns2 on 2025-03-28T15:05:30+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sample-sns'
primary_region = 'sea'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2

[deploy]
  release_command = "bin/rails db:migrate"

[mounts]
  source = "data"
  destination = "/data"
