\default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['sample-db'] %>
  password: <%= ENV['rLpo8SNki9fjMPoAUl0ClZW6Q9CI3Kgo'] %>
  host: <%= ENV['dpg-cvqb371r0fns73em1q40-a'] %>
  port: <%= ENV['5432'] %>

development:
  <<: *default
  database: <%= ENV['sample_db_0t0w'] || 'your_database_name_development' %>

test:
  <<: *default
  database: <%= ENV['sample_db_0t0w'] || 'your_database_name_test' %>

production:
  primary:
    <<: *default
    database: <%= ENV['sample_db_0t0w'] || 'your_database_name_production' %>
  cache:
    <<: *default
    database: <%= ENV['sample_db_0t0w'] || 'your_database_name_cache' %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV['sample_db_0t0w'] || 'your_database_name_queue' %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV['sample_db_0t0w'] || 'your_database_name_cable' %>
    migrations_paths: db/cable_migrate
