default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME_DEVELOPMENT'] || 'your_database_name_development' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME_TEST'] || 'your_database_name_test' %>

production:
  primary:
    <<: *default
    database: <%= ENV['DATABASE_NAME_PRODUCTION'] || 'your_database_name_production' %>
  cache:
    <<: *default
    database: <%= ENV['DATABASE_NAME_CACHE'] || 'your_database_name_cache' %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV['DATABASE_NAME_QUEUE'] || 'your_database_name_queue' %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV['DATABASE_NAME_CABLE'] || 'your_database_name_cable' %>
    migrations_paths: db/cable_migrate
